# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc161d6625c0859c470294a98db45379a484177ba52e19ff4ef8a622fc6c32f6e723b103de79d958d2c411f3898d568a3a88e6f4acca5e792aba88da6f89dff4

test:
  secret_key_base: 3f8c04aae0aeae77dd6f33f078dde5009d94bec4fee30bcdf8864be08bb9c8816be84104ba54cae25e6919170c1f37c95b12a0dfb65d41459b287f01e6cfb600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
